-- View created to avoid having to expose all PII data publicly to be able to run hackathon results
CREATE OR REPLACE VIEW `chainlink-marketing-roi.ga_export.ga_stream` AS
SELECT
  clientId,
  userId,
  fullVisitorId,
  visitId,
  visitNumber,
  date,
  timestamp_utc,
  timestamp_local,
  date_calendar,
  insertionId,
  ga_property,
  trafficSource.adContent as trafficSource_adContent,
  trafficSource.campaign as trafficSource_campaign,
  trafficSource.campaignCode as trafficSource_campaignCode,
  trafficSource.medium as trafficSource_medium,
  trafficSource.referralPath as trafficSource_referralPath,
  trafficSource.source as trafficSource_source,
  device.deviceCategory,
  device.isMobile,
  device.browser,
  device.browserVersion,
  device.browserSize,
  device.mobileDeviceInfo,
  device.mobileDeviceModel,
  device.mobileInputSelector,
  device.operatingSystem,
  device.operatingSystemVersion,
  device.mobileDeviceBranding,
  device.flashVersion,
  device.javaEnabled,
  device.language,
  device.screenColours,
  device.screenResolution,
  geoNetwork.continent,
  geoNetwork.subContinent,
  geoNetwork.country,
  geoNetwork.region
FROM
  `nessie-dev-030719-111015.fourcast.ua1258111401_stream`